//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSucursal.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public string rut_administrador { get; set; }
        public string nombre_administrador { get; set; }
        public string sexo_administrador { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
